disabled_rules: # rule identifiers to exclude from running
  - line_length                 #not enabling doesn't work correctly (still beta 0.7)
  - todo                        #not enabling since we have own build script phase
  - trailing_whitespace
  - cyclomatic_complexity       #should discuss, in beta 0.7 still sorting out calculation
  - function_parameter_count
  - unused_optional_binding
  - redundant_discardable_let
opt_in_rules:
  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
statement_position:
  statement_mode: uncuddled_else # this enables us to place the else on a the next line from the closing brace of the if
type_name:
  min_length: 3 # only warning
  max_length: # warning
    warning: 50
    error: 60
file_length:
    warning: 1000
    error: 1500
function_body_length:
    warning: 120
    error: 160
type_body_length:
    warning: 450
    error: 800
variable_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
force_unwrapping:
    error
vertical_whitespace:
  severity: error
